spring:
  application:
    name: auth
  redis:
    host: localhost
    port: 6379
    database: 1
    jedis:
      pool:
        max-idle: 100
        max-active: 100
        max-wait: 1000
        min-idle: 10



server:
  port: 8001

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server1:9001/eureka/,http://eureka-server2:9002/eureka/

