spring:
  application:
    name: eureka
server:
  port: 9002

## eureka 集群2
eureka:
  instance:
    hostname: eureka-server2
#    prefer-ip-address: true # 当调用getHostname获取实例的hostname时，返回ip而不是host名称
#    ip-address: 127.0.0.1 # 指定自己的ip信息，不指定的话会自己寻找
  client:
    # 是否将自己注册到eureka
    register-with-eureka: false
    # 是否从eureka server获取注册信息
    fetch-registry: false
    # 设置与eureka server 交互的地址 查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
    service-url:
      defaultZone: http://eureka-server1:9001/eureka/

